RobotConfig:
  robot_name: "efc"
  type: "gz"
  joint_size: 24
  motor_size: 24
  switching_time: 0.50
  joint_names: &joint_names
    - "l_hip_p"
    - "l_hip_r"
    - "l_hip_y"
    - "l_knee"
    - "l_ankle_p"
    - "l_ankle_r"
    - "r_hip_p"
    - "r_hip_r"
    - "r_hip_y"
    - "r_knee"
    - "r_ankle_p"
    - "r_ankle_r"
    - "waist_y"
    - "l_shoulder_p"
    - "l_shoulder_r"
    - "l_shoulder_y"
    - "l_elbow_p"
    - "l_elbow_y"
    - "r_shoulder_p"
    - "r_shoulder_r"
    - "r_shoulder_y"
    - "r_elbow_p"
    - "r_elbow_y"
    - "head_y"
  motor_names: *joint_names

  motor_direction:
    l_hip_p: 1
    l_hip_r: 1
    l_hip_y: 1
    l_knee: 1
    l_ankle_p: 1
    l_ankle_r: 1
    r_hip_p: 1
    r_hip_r: 1
    r_hip_y: 1
    r_knee: 1
    r_ankle_p: 1
    r_ankle_r: 1
    waist_y: 1
    l_shoulder_p: 1
    l_shoulder_r: 1
    l_shoulder_y: 1
    l_elbow_p: 1
    l_elbow_y: 1
    r_shoulder_p: 1
    r_shoulder_r: 1
    r_shoulder_y: 1
    r_elbow_p: 1
    r_elbow_y: 1
    head_y: 1

  observer:
    log_data:  true
    log_dir: "/home/dknt/Project/bitbot_gz_ws/src/bitbot_gz/log/extra"
    motor_pos_filter:
      type: "PassThrough"
      lower_bound: [ 
                     -3.14, -3.14, -3.14, -3.14, -3.14, -3.14,
                     -3.14, -3.14, -3.14, -3.14, -3.14, -3.14,
                     -3.14,
                     -3.14, -3.14, -3.14, -3.14, -3.14,
                     -3.14, -3.14, -3.14, -3.14, -3.14,
                     -3.14,
                   ]
      upper_bound: [
                     3.14, 3.14, 3.14, 3.14, 3.14, 3.14,
                     3.14, 3.14, 3.14, 3.14, 3.14, 3.14,
                     3.14,
                     3.14, 3.14, 3.14, 3.14, 3.14,
                     3.14, 3.14, 3.14, 3.14, 3.14,
                     3.14,
                   ]
    motor_vel_filter:
      type: "Mean"
      history_length: 3
      lower_bound: [
                     -50, -50, -50, -50, -50, -50,
                     -50, -50, -50, -50, -50, -50,
                     -50,
                     -50, -50, -50, -50, -50,
                     -50, -50, -50, -50, -50,
                     -50,
                   ]
      upper_bound: [
                     50, 50, 50, 50, 50, 50,
                     50, 50, 50, 50, 50, 50,
                     50,
                     50, 50, 50, 50, 50,
                     50, 50, 50, 50, 50,
                     50,
                   ]
    ang_vel_filter:
      type: "PassThrough"
      upper_bound: [100.0, 100.0, 100.0]
      lower_bound: [-100.0, -100.0, -100.0]
    acc_filter:
      type: "PassThrough"
      upper_bound: [100.0, 100.0, 100.0]
      lower_bound: [-100.0, -100.0, -100.0]
    euler_filter:
      type: "PassThrough"
      upper_bound: [100.0, 100.0, 100.0]
      lower_bound: [-100.0, -100.0, -100.0]

  executor:
    torque_limit:  # Nm
      l_hip_p: 500
      l_hip_r: 500
      l_hip_y: 500
      l_knee: 500
      l_ankle_p: 500
      l_ankle_r: 500
      r_hip_p: 500
      r_hip_r: 500
      r_hip_y: 500
      r_knee: 500
      r_ankle_p: 500
      r_ankle_r: 500
      waist_y: 500
      l_shoulder_p: 500
      l_shoulder_r: 500
      l_shoulder_y: 500
      l_elbow_p: 500
      l_elbow_y: 500
      r_shoulder_p: 500
      r_shoulder_r: 500
      r_shoulder_y: 500
      r_elbow_p: 500
      r_elbow_y: 500
      head_y: 500
    motor_upper_limit:  # rad
      l_hip_p: 3.14
      l_hip_r: 3.14
      l_hip_y: 3.14
      l_knee: 3.14
      l_ankle_p: 3.14
      l_ankle_r: 3.14
      r_hip_p: 3.14
      r_hip_r: 3.14
      r_hip_y: 3.14
      r_knee: 3.14
      r_ankle_p: 3.14
      r_ankle_r: 3.14
      waist_y: 3.14
      l_shoulder_p: 3.14
      l_shoulder_r: 3.14
      l_shoulder_y: 3.14
      l_elbow_p: 3.14
      l_elbow_y: 3.14
      r_shoulder_p: 3.14
      r_shoulder_r: 3.14
      r_shoulder_y: 3.14
      r_elbow_p: 3.14
      r_elbow_y: 3.14
      head_y: 3.14
    motor_lower_limit:  # rad
      l_hip_p: -3.14
      l_hip_r: -3.14
      l_hip_y: -3.14
      l_knee: -3.14
      l_ankle_p: -3.14
      l_ankle_r: -3.14
      r_hip_p: -3.14
      r_hip_r: -3.14
      r_hip_y: -3.14
      r_knee: -3.14
      r_ankle_p: -3.14
      r_ankle_r: -3.14
      waist_y: -3.14
      l_shoulder_p: -3.14
      l_shoulder_r: -3.14
      l_shoulder_y: -3.14
      l_elbow_p: -3.14
      l_elbow_y: -3.14
      r_shoulder_p: -3.14
      r_shoulder_r: -3.14
      r_shoulder_y: -3.14
      r_elbow_p: -3.14
      r_elbow_y: -3.14
      head_y: -3.14

  init_pos:
    duration: 1.5
    init_position: &defult_init_pos
      l_hip_p: -0.3
      l_hip_r: 0
      l_hip_y: 0
      l_knee: 0.6
      l_ankle_p: -0.3
      l_ankle_r: 0
      r_hip_p: -0.3
      r_hip_r: 0
      r_hip_y: 0
      r_knee: 0.6
      r_ankle_p: -0.3
      r_ankle_r: 0
      waist_y: 0
      l_shoulder_p: 0.3
      l_shoulder_r: 0.1
      l_shoulder_y: 0
      l_elbow_p: -0.8
      l_elbow_y: 0
      r_shoulder_p: 0.3
      r_shoulder_r: -0.1
      r_shoulder_y: 0
      r_elbow_p: -0.8
      r_elbow_y: 0
      head_y: 0

    p_gains: &default_p_gains
      l_hip_p: 150
      l_hip_r: 150
      l_hip_y: 100
      l_knee: 150
      l_ankle_p: 30
      l_ankle_r: 30
      r_hip_p: 150
      r_hip_r: 150
      r_hip_y: 100
      r_knee: 150
      r_ankle_p: 30
      r_ankle_r: 30
      waist_y: 100
      l_shoulder_p: 30
      l_shoulder_r: 20
      l_shoulder_y: 10
      l_elbow_p: 10
      l_elbow_y: 10
      r_shoulder_p: 30
      r_shoulder_r: 20
      r_shoulder_y: 10
      r_elbow_p: 10
      r_elbow_y: 10
      head_y: 30

    d_gains: &default_d_gains
      l_hip_p: 3.0
      l_hip_r: 3.0
      l_hip_y: 3.0
      l_knee: 3.0
      l_ankle_p: 2.0
      l_ankle_r: 2.0
      r_hip_p: 3.0
      r_hip_r: 3.0
      r_hip_y: 3.0
      r_knee: 3.0
      r_ankle_p: 2.0
      r_ankle_r: 2.0
      waist_y: 3.0
      l_shoulder_p: 2.0
      l_shoulder_r: 2.0
      l_shoulder_y: 2.0
      l_elbow_p: 2.0
      l_elbow_y: 2.0
      r_shoulder_p: 2.0
      r_shoulder_r: 2.0
      r_shoulder_y: 2.0
      r_elbow_p: 2.0
      r_elbow_y: 2.0
      head_y: 2.0

  zero_pos:
    duration: 1.0
    init_position: *defult_init_pos
    p_gains: *default_p_gains
    d_gains: *default_d_gains

  policy_standing:
    controller_type: "AUTO"
    num_delay: 0
    p_gains:
      l_hip_p: 150
      l_hip_r: 150
      l_hip_y: 100
      l_knee: 150
      l_ankle_p: 30
      l_ankle_r: 30
      r_hip_p: 150
      r_hip_r: 150
      r_hip_y: 100
      r_knee: 150
      r_ankle_p: 30
      r_ankle_r: 30
      waist_y: 100
      l_shoulder_p: 30
      l_shoulder_r: 20
      l_shoulder_y: 10
      l_elbow_p: 10
      l_elbow_y: 10
      r_shoulder_p: 30
      r_shoulder_r: 20
      r_shoulder_y: 10
      r_elbow_p: 10
      r_elbow_y: 10
      head_y: 30
    d_gains:
      l_hip_p: 3.0
      l_hip_r: 3.0
      l_hip_y: 3.0
      l_knee: 3.0
      l_ankle_p: 2.0
      l_ankle_r: 2.0
      r_hip_p: 3.0
      r_hip_r: 3.0
      r_hip_y: 3.0
      r_knee: 3.0
      r_ankle_p: 2.0
      r_ankle_r: 2.0
      waist_y: 3.0
      l_shoulder_p: 2.0
      l_shoulder_r: 2.0
      l_shoulder_y: 2.0
      l_elbow_p: 2.0
      l_elbow_y: 2.0
      r_shoulder_p: 2.0
      r_shoulder_r: 2.0
      r_shoulder_y: 2.0
      r_elbow_p: 2.0
      r_elbow_y: 2.0
      head_y: 2.0
    default_position: *defult_init_pos
    decimation: 10
    target_pos_filter: &default_target_pos_filter
      type: "None"

    inference:
      policy_type: "Epsilon"
      use_absolute_clock: true
      control_period: 0.01
      model_path: "/home/dknt/Project/bitbot_gz_ws/src/bitbot_gz/checkpoint/efc/theta_3d_v43.onnx"
      obs_buffer_size: 15

      log_data: true
      log_dir: "/home/dknt/Project/bitbot_gz_ws/src/bitbot_gz/log/policy"
      log_name: "standing"

      device: "CPU"
      single_obs_size: 72
      action_size: 21
      action_scale: 0.25
      obs_scales:
        ang_vel: 1.0
        lin_vel: 2.0
        command: 1.0
        dof_pos: 1.0
        dof_vel: 0.05
        proj_gravity: 1.0
      clip_action: 18.0
      realtime: false
      stick_to_core: 5

      policy_joint_names:
        - "l_hip_p"
        - "l_hip_r"
        - "l_hip_y"
        - "l_knee"
        - "l_ankle_p"
        - "l_ankle_r"
        - "r_hip_p"
        - "r_hip_r"
        - "r_hip_y"
        - "r_knee"
        - "r_ankle_p"
        - "r_ankle_r"
        - "waist_y"
        - "l_shoulder_p"
        - "l_shoulder_r"
        - "l_shoulder_y"
        - "l_elbow_p"
        - "r_shoulder_p"
        - "r_shoulder_r"
        - "r_shoulder_y"
        - "r_elbow_p"
      policy_default_position:
        l_hip_p: -0.15
        l_hip_r: 0
        l_hip_y: 0
        l_knee: 0.3
        l_ankle_p: -0.15
        l_ankle_r: 0
        r_hip_p: -0.15
        r_hip_r: 0
        r_hip_y: 0
        r_knee: 0.3
        r_ankle_p: -0.15
        r_ankle_r: 0
        waist_y: 0
        l_shoulder_p: 0.3
        l_shoulder_r: 0.1
        l_shoulder_y: 0
        l_elbow_p: -0.8
        l_elbow_y: 0
        r_shoulder_p: 0.3
        r_shoulder_r: -0.1
        r_shoulder_y: 0
        r_elbow_p: -0.8
        r_elbow_y: 0
        head_y: 0

  policy_walking:
    controller_type: "AUTO"
    num_delay: 0
    p_gains:
      l_hip_p: 150
      l_hip_r: 150
      l_hip_y: 100
      l_knee: 150
      l_ankle_p: 30
      l_ankle_r: 30
      r_hip_p: 150
      r_hip_r: 150
      r_hip_y: 100
      r_knee: 150
      r_ankle_p: 30
      r_ankle_r: 30
      waist_y: 100
      l_shoulder_p: 50
      l_shoulder_r: 50
      l_shoulder_y: 50
      l_elbow_p: 50
      l_elbow_y: 50
      r_shoulder_p: 50
      r_shoulder_r: 50
      r_shoulder_y: 50
      r_elbow_p: 50
      r_elbow_y: 50
      head_y: 30
    d_gains:
      l_hip_p: 3.0
      l_hip_r: 3.0
      l_hip_y: 3.0
      l_knee: 3.0
      l_ankle_p: 2.0
      l_ankle_r: 2.0
      r_hip_p: 3.0
      r_hip_r: 3.0
      r_hip_y: 3.0
      r_knee: 3.0
      r_ankle_p: 2.0
      r_ankle_r: 2.0
      waist_y: 3.0
      l_shoulder_p: 2.0
      l_shoulder_r: 2.0
      l_shoulder_y: 2.0
      l_elbow_p: 2.0
      l_elbow_y: 2.0
      r_shoulder_p: 2.0
      r_shoulder_r: 2.0
      r_shoulder_y: 2.0
      r_elbow_p: 2.0
      r_elbow_y: 2.0
      head_y: 2.0
    default_position: *defult_init_pos
    decimation: 20
    target_pos_filter: *default_target_pos_filter

    inference:
      # policy_type: "Epsilon"
      policy_type: "Hike"
      # policy_type: "HikeClock"
      use_absolute_clock: false
      control_period: 0.02
      cycle_time: 0.9
      # TODO:
      model_path: "/home/dknt/Project/bitbot_gz_ws/src/bitbot_gz/checkpoint/efc/50_dm_3.onnx"
      # model_path: "/home/dknt/Project/bitbot_gz_ws/src/bitbot_gz/checkpoint/efc/stair_50_v4.onnx"
      # model_path: "/home/dknt/Project/bitbot_gz_ws/src/bitbot_gz/checkpoint/efc/parkour_stair_noised.onnx"
      # model_path: "/home/dknt/Project/bitbot_gz_ws/src/bitbot_gz/checkpoint/efc/parkour_stair_v31.onnx"
      # model_path: "/home/dknt/Project/bitbot_gz_ws/src/bitbot_gz/checkpoint/efc/parkour_noised.onnx"
      # model_path: "/home/dknt/Project/bitbot_gz_ws/src/bitbot_gz/checkpoint/efc/amp_parkour_v8.onnx"
      # model_path: "/home/dknt/Project/bitbot_gz_ws/src/bitbot_gz/checkpoint/efc/parkour_test3.onnx"
      obs_buffer_size: 8
      num_images: 8
      # image_skip: 5
      image_skip: 10
      # image_skip: 15
      # image_skip: 0
      image_width: 32
      image_height: 18

      log_data: true
      log_dir: "/home/dknt/Project/bitbot_gz_ws/src/bitbot_gz/log/policy"
      log_name: "walking"

      device: "CPU"
      single_obs_size: 72
      action_size: 21
      action_scale: 0.25
      obs_scales:
        ang_vel: 0.25
        lin_vel: 1.0
        command: 1.0
        dof_pos: 1.0
        dof_vel: 0.05
        proj_gravity: 1.0
      clip_action: 18.0
      realtime: false
      stick_to_core: 5

      policy_joint_names:
        - "l_hip_p"
        - "r_hip_p"
        - "waist_y"
        - "l_hip_r"
        - "r_hip_r"
        - "l_shoulder_p"
        - "r_shoulder_p"
        - "l_hip_y"
        - "r_hip_y"
        - "l_shoulder_r"
        - "r_shoulder_r"
        - "l_knee"
        - "r_knee"
        - "l_shoulder_y"
        - "r_shoulder_y"
        - "l_ankle_p"
        - "r_ankle_p"
        - "l_elbow_p"
        - "r_elbow_p"
        - "l_ankle_r"
        - "r_ankle_r"
      policy_default_position:
        # l_hip_p: -0.15
        # r_hip_p: -0.15
        l_hip_p: -0.25
        r_hip_p: -0.25
        waist_y: 0
        l_hip_r: 0
        r_hip_r: 0
        l_shoulder_p: 0.3
        r_shoulder_p: 0.3
        l_hip_y: 0
        r_hip_y: 0
        l_shoulder_r: 0.1
        r_shoulder_r: -0.1
        # l_knee: 0.3
        # r_knee: 0.3
        l_knee: 0.5
        r_knee: 0.5
        l_shoulder_y: 0
        r_shoulder_y: 0
        # l_ankle_p: -0.15
        # r_ankle_p: -0.15
        l_ankle_p: -0.25
        r_ankle_p: -0.25
        l_elbow_p: -0.8
        r_elbow_p: -0.8
        l_ankle_r: 0
        r_ankle_r: 0

  # policy_robust:
  #   controller_type: "AUTO"
  #   num_delay: 0
  #   p_gains:
  #     l_hip_p: 150
  #     l_hip_r: 150
  #     l_hip_y: 100
  #     l_knee: 150
  #     l_ankle_p: 30
  #     l_ankle_r: 30
  #     r_hip_p: 150
  #     r_hip_r: 150
  #     r_hip_y: 100
  #     r_knee: 150
  #     r_ankle_p: 30
  #     r_ankle_r: 30
  #     waist_y: 100
  #     l_shoulder_p: 50
  #     l_shoulder_r: 50
  #     l_shoulder_y: 50
  #     l_elbow_p: 50
  #     l_elbow_y: 50
  #     r_shoulder_p: 50
  #     r_shoulder_r: 50
  #     r_shoulder_y: 50
  #     r_elbow_p: 50
  #     r_elbow_y: 50
  #     head_y: 30
  #   d_gains:
  #     l_hip_p: 3.0
  #     l_hip_r: 3.0
  #     l_hip_y: 3.0
  #     l_knee: 3.0
  #     l_ankle_p: 2.0
  #     l_ankle_r: 2.0
  #     r_hip_p: 3.0
  #     r_hip_r: 3.0
  #     r_hip_y: 3.0
  #     r_knee: 3.0
  #     r_ankle_p: 2.0
  #     r_ankle_r: 2.0
  #     waist_y: 3.0
  #     l_shoulder_p: 2.0
  #     l_shoulder_r: 2.0
  #     l_shoulder_y: 2.0
  #     l_elbow_p: 2.0
  #     l_elbow_y: 2.0
  #     r_shoulder_p: 2.0
  #     r_shoulder_r: 2.0
  #     r_shoulder_y: 2.0
  #     r_elbow_p: 2.0
  #     r_elbow_y: 2.0
  #     head_y: 2.0
  #   default_position: *defult_init_pos
  #   decimation: 20
  #   target_pos_filter: *default_target_pos_filter
  #
  #   inference:
  #     policy_type: "BeyondMimic"
  #     use_absolute_clock: true
  #     control_period: 0.02
  #     model_path: "/home/dknt/Project/bitbot_gz_ws/src/bitbot_gz/checkpoint/efc/dance1.onnx"
  #     obs_buffer_size: 1
  #
  #     log_data: true
  #     log_dir: "/home/dknt/Project/bitbot_gz_ws/src/bitbot_gz/log/policy"
  #     log_name: "robust"
  #
  #     device: "CPU"
  #     single_obs_size: 124
  #     action_size: 23
  #     action_scale: 0.25
  #     obs_scales:
  #       ang_vel: 1.0
  #       lin_vel: 1.0
  #       command: 1.0
  #       dof_pos: 1.0
  #       dof_vel: 1.0
  #       proj_gravity: 1.0
  #     clip_action: 18.0
  #     realtime: false
  #     stick_to_core: 5
  #
  #     policy_joint_names:
  #       - "l_hip_p"
  #       - "r_hip_p"
  #       - "waist_y"
  #       - "l_hip_r"
  #       - "r_hip_r"
  #       - "l_shoulder_p"
  #       - "r_shoulder_p"
  #       - "l_hip_y"
  #       - "r_hip_y"
  #       - "l_shoulder_r"
  #       - "r_shoulder_r"
  #       - "l_knee"
  #       - "r_knee"
  #       - "l_shoulder_y"
  #       - "r_shoulder_y"
  #       - "l_ankle_p"
  #       - "r_ankle_p"
  #       - "l_elbow_p"
  #       - "r_elbow_p"
  #       - "l_ankle_r"
  #       - "r_ankle_r"
  #       - "l_elbow_y"
  #       - "r_elbow_y"
  #     policy_default_position:
  #       l_hip_p: -0.25
  #       r_hip_p: -0.25
  #       waist_y: 0
  #       l_hip_r: 0
  #       r_hip_r: 0
  #       l_shoulder_p: 0.3
  #       r_shoulder_p: 0.3
  #       l_hip_y: 0
  #       r_hip_y: 0
  #       l_shoulder_r: 0.1
  #       r_shoulder_r: -0.1
  #       l_knee: 0.5
  #       r_knee: 0.5
  #       l_shoulder_y: 0
  #       r_shoulder_y: 0
  #       l_ankle_p: -0.25
  #       r_ankle_p: -0.25
  #       l_elbow_p: -0.8
  #       r_elbow_p: -0.8
  #       l_ankle_r: 0
  #       r_ankle_r: 0
  #       l_elbow_y: 0
  #       r_elbow_y: 0
  policy_robust:
    controller_type: "AUTO"
    p_gains:
      l_hip_p: 150
      l_hip_r: 150
      l_hip_y: 100
      l_knee: 150
      l_ankle_p: 30
      l_ankle_r: 30
      r_hip_p: 150
      r_hip_r: 150
      r_hip_y: 100
      r_knee: 150
      r_ankle_p: 30
      r_ankle_r: 30
      waist_y: 200
      l_shoulder_p: 30
      l_shoulder_r: 20
      l_shoulder_y: 10
      l_elbow_p: 10
      l_elbow_y: 10
      r_shoulder_p: 30
      r_shoulder_r: 20
      r_shoulder_y: 10
      r_elbow_p: 10
      r_elbow_y: 10
      head_y: 30
    d_gains:
      l_hip_p: 1.5
      l_hip_r: 1.5
      l_hip_y: 1.5
      l_knee: 1.5
      l_ankle_p: 1.0
      l_ankle_r: 1.0
      r_hip_p: 1.5
      r_hip_r: 1.5
      r_hip_y: 1.5
      r_knee: 1.5
      r_ankle_p: 1.0
      r_ankle_r: 1.0
      waist_y: 2.0
      l_shoulder_p: 1.0
      l_shoulder_r: 1.0
      l_shoulder_y: 1.0
      l_elbow_p: 1.0
      l_elbow_y: 1.0
      r_shoulder_p: 1.0
      r_shoulder_r: 1.0
      r_shoulder_y: 1.0
      r_elbow_p: 1.0
      r_elbow_y: 1.0
      head_y: 1.0
    default_position: *defult_init_pos
    decimation: 10
    target_pos_filter: *default_target_pos_filter

    inference:
      policy_type: "Locomotion"
      use_absolute_clock: true
      control_period: 0.01
      model_path: "/home/dknt/Project/bitbot_gz_ws/src/bitbot_gz/checkpoint/efc/delta_terrain.onnx"
      obs_buffer_size: 15
      cycle_time: 0.8
      phase_offset_left: 0.38
      phase_offset_right: 0.88

      log_data: true
      log_dir: "/home/dknt/Project/bitbot_gz_ws/src/bitbot_gz/log/policy"
      log_name: "robust"

      device: "CPU"
      single_obs_size: 50
      action_size: 13
      action_scale: 0.5 #  0.25
      obs_scales:
        ang_vel: 1.0
        lin_vel: 2.0
        command: 1.0
        dof_pos: 1.0
        dof_vel: 0.05
        proj_gravity: 1.0
      clip_action: 18.0
      realtime: true
      stick_to_core: 7

      policy_joint_names:
        - "l_hip_p"
        - "l_hip_r"
        - "l_hip_y"
        - "l_knee"
        - "l_ankle_p"
        - "l_ankle_r"
        - "r_hip_p"
        - "r_hip_r"
        - "r_hip_y"
        - "r_knee"
        - "r_ankle_p"
        - "r_ankle_r"
        - "waist_y"
      policy_default_position:
        l_hip_p: -0.3
        l_hip_r: 0
        l_hip_y: 0
        l_knee: 0.6
        l_ankle_p: -0.3
        l_ankle_r: 0
        r_hip_p: -0.3
        r_hip_r: 0
        r_hip_y: 0
        r_knee: 0.6
        r_ankle_p: -0.3
        r_ankle_r: 0
        waist_y: 0
